name: Deploy Vue 3 Project

on:
  push:
    branches:
      - main  # Change this to your deployment branch if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build-only

    - name: Copy files via SCP
      run: |
        scp -r -o StrictHostKeyChecking=no dist/* amr@209.38.198.225:/var/www/majesticminds.net/dist

    - name: Execute remote commands
      run: |
        ssh -o StrictHostKeyChecking=no amr@209.38.198.225 << 'EOF'
          cd /var/www/majesticminds.net
          # Example command to restart the web server (adjust as needed)
          sudo systemctl restart apache2
        EOF
